
-- Add division_level column to ncaa_football_schools
ALTER TABLE public.ncaa_football_schools 
ADD COLUMN IF NOT EXISTS division_level text DEFAULT 'D1-FBS';

-- Update existing schools to be D1-FBS
UPDATE public.ncaa_football_schools SET division_level = 'D1-FBS' WHERE division_level IS NULL;

-- Insert D1-FCS schools
INSERT INTO public.ncaa_football_schools (name, state, conference, division_level, city) VALUES
('Alabama State', 'Alabama', 'SWAC', 'D1-FCS', NULL),
('Alcorn State', 'Mississippi', 'SWAC', 'D1-FCS', NULL),
('Arkansas-Pine Bluff', 'Arkansas', 'SWAC', 'D1-FCS', NULL),
('Austin Peay', 'Tennessee', 'UAC', 'D1-FCS', NULL),
('Bethune-Cookman', 'Florida', 'MEAC', 'D1-FCS', NULL),
('Brown University', 'Rhode Island', 'Ivy League', 'D1-FCS', NULL),
('Bryant University', 'Rhode Island', 'NEC', 'D1-FCS', NULL),
('Bucknell', 'Pennsylvania', 'Patriot League', 'D1-FCS', NULL),
('Campbell University', 'North Carolina', 'Big South', 'D1-FCS', NULL),
('Central Arkansas', 'Arkansas', 'UAC', 'D1-FCS', NULL),
('Charleston Southern', 'South Carolina', 'Big South', 'D1-FCS', NULL),
('Colgate University', 'New York', 'Patriot League', 'D1-FCS', NULL),
('Columbia University', 'New York', 'Ivy League', 'D1-FCS', NULL),
('Cornell', 'New York', 'Ivy League', 'D1-FCS', NULL),
('Dartmouth', 'New Hampshire', 'Ivy League', 'D1-FCS', NULL),
('Delaware', 'Delaware', 'CAA', 'D1-FCS', NULL),
('Delaware State', 'Delaware', 'MEAC', 'D1-FCS', NULL),
('Duquesne', 'Pennsylvania', 'NEC', 'D1-FCS', NULL),
('Eastern Kentucky', 'Kentucky', 'UAC', 'D1-FCS', NULL),
('Elon', 'North Carolina', 'CAA', 'D1-FCS', NULL),
('Florida A&M', 'Florida', 'MEAC', 'D1-FCS', NULL),
('Furman', 'South Carolina', 'SOCON', 'D1-FCS', NULL),
('Gardner-Webb', 'North Carolina', 'Big South', 'D1-FCS', NULL),
('Georgetown University', 'Washington DC', 'Patriot League', 'D1-FCS', NULL),
('Grambling State', 'Louisiana', 'SWAC', 'D1-FCS', NULL),
('Howard University', 'Washington DC', 'MEAC', 'D1-FCS', NULL),
('Illinois State', 'Illinois', 'Missouri Valley', 'D1-FCS', NULL),
('Lafayette College', 'Pennsylvania', 'Patriot League', 'D1-FCS', NULL),
('Lamar University', 'Texas', 'Southland', 'D1-FCS', NULL),
('Lehigh', 'Pennsylvania', 'Patriot League', 'D1-FCS', NULL),
('Lindenwood University', 'Missouri', 'OVC', 'D1-FCS', NULL),
('LIU', 'New York', 'NEC', 'D1-FCS', NULL),
('Maine', 'Maine', 'CAA', 'D1-FCS', NULL),
('Marist', 'New York', 'Pioneer League', 'D1-FCS', NULL),
('McNeese State', 'Louisiana', 'Southland', 'D1-FCS', NULL),
('Mercer', 'Georgia', 'SOCON', 'D1-FCS', NULL),
('Merrimack College', 'Massachusetts', 'NEC', 'D1-FCS', NULL),
('Mississippi Valley State', 'Mississippi', 'SWAC', 'D1-FCS', NULL),
('Missouri State', 'Missouri', 'Missouri Valley', 'D1-FCS', NULL),
('New Hampshire', 'New Hampshire', 'CAA', 'D1-FCS', NULL),
('Norfolk State', 'Virginia', 'MEAC', 'D1-FCS', NULL),
('North Carolina A&T', 'North Carolina', 'CAA', 'D1-FCS', NULL),
('North Carolina Central', 'North Carolina', 'MEAC', 'D1-FCS', NULL),
('North Dakota State', 'North Dakota', 'Missouri Valley', 'D1-FCS', NULL),
('Penn', 'Pennsylvania', 'Ivy League', 'D1-FCS', NULL),
('Prairie View A&M', 'Texas', 'SWAC', 'D1-FCS', NULL),
('Presbyterian College', 'South Carolina', 'Pioneer League', 'D1-FCS', NULL),
('Princeton', 'New Jersey', 'Ivy League', 'D1-FCS', NULL),
('Richmond', 'Virginia', 'CAA', 'D1-FCS', NULL),
('Sacred Heart', 'Connecticut', 'NEC', 'D1-FCS', NULL),
('Sam Houston State', 'Texas', 'WAC', 'D1-FCS', NULL),
('Samford', 'Alabama', 'SOCON', 'D1-FCS', NULL),
('South Dakota', 'South Dakota', 'Missouri Valley', 'D1-FCS', NULL),
('Southern Illinois', 'Illinois', 'Missouri Valley', 'D1-FCS', NULL),
('Stetson', 'Florida', 'Pioneer League', 'D1-FCS', NULL),
('Stony Brook', 'New York', 'CAA', 'D1-FCS', NULL),
('Tennessee State', 'Tennessee', 'OVC', 'D1-FCS', NULL),
('Texas A&M-Commerce', 'Texas', 'Southland', 'D1-FCS', NULL),
('Towson', 'Maryland', 'CAA', 'D1-FCS', NULL),
('UT Martin', 'Tennessee', 'OVC', 'D1-FCS', NULL),
('Valparaiso University', 'Indiana', 'Pioneer League', 'D1-FCS', NULL),
('VMI', 'Virginia', 'SOCON', 'D1-FCS', NULL),
('Western Carolina', 'North Carolina', 'SOCON', 'D1-FCS', NULL),
('William & Mary', 'Virginia', 'CAA', 'D1-FCS', NULL),
('Yale', 'Connecticut', 'Ivy League', 'D1-FCS', NULL)
ON CONFLICT (name) DO NOTHING;
