-- Insert D1-FCS schools
INSERT INTO public.ncaa_football_schools (name, state, division_level, conference) VALUES
('Alabama State', 'Alabama', 'D1-FCS', 'SWAC'),
('Alcorn State', 'Mississippi', 'D1-FCS', 'SWAC'),
('Arkansas-Pine Bluff', 'Arkansas', 'D1-FCS', 'SWAC'),
('Austin Peay', 'Tennessee', 'D1-FCS', 'UAC'),
('Bethune-Cookman', 'Florida', 'D1-FCS', 'MEAC'),
('Brown University', 'Rhode Island', 'D1-FCS', 'Ivy League'),
('Bryant University', 'Rhode Island', 'D1-FCS', 'NEC'),
('Bucknell', 'Pennsylvania', 'D1-FCS', 'Patriot League'),
('Campbell University', 'North Carolina', 'D1-FCS', 'Big South'),
('Central Arkansas', 'Arkansas', 'D1-FCS', 'UAC'),
('Charleston Southern', 'South Carolina', 'D1-FCS', 'Big South'),
('Colgate University', 'New York', 'D1-FCS', 'Patriot League'),
('Columbia University', 'New York', 'D1-FCS', 'Ivy League'),
('Cornell', 'New York', 'D1-FCS', 'Ivy League'),
('Dartmouth', 'New Hampshire', 'D1-FCS', 'Ivy League'),
('Delaware', 'Delaware', 'D1-FCS', 'CAA'),
('Delaware State', 'Delaware', 'D1-FCS', 'MEAC'),
('Duquesne', 'Pennsylvania', 'D1-FCS', 'NEC'),
('Eastern Kentucky', 'Kentucky', 'D1-FCS', 'UAC'),
('Elon', 'North Carolina', 'D1-FCS', 'CAA'),
('Florida A&M', 'Florida', 'D1-FCS', 'MEAC'),
('Furman', 'South Carolina', 'D1-FCS', 'SOCON'),
('Gardner-Webb', 'North Carolina', 'D1-FCS', 'Big South'),
('Georgetown University', 'Washington DC', 'D1-FCS', 'Patriot League'),
('Grambling State University', 'Louisiana', 'D1-FCS', 'SWAC'),
('Howard University', 'Washington DC', 'D1-FCS', 'MEAC'),
('Illinois State', 'Illinois', 'D1-FCS', 'Missouri Valley'),
('Lafayette College', 'Pennsylvania', 'D1-FCS', 'Patriot League'),
('Lamar University', 'Texas', 'D1-FCS', 'Southland'),
('Lehigh', 'Pennsylvania', 'D1-FCS', 'Patriot League'),
('Lindenwood University', 'Missouri', 'D1-FCS', 'OVC'),
('LIU', 'New York', 'D1-FCS', 'NEC'),
('Maine', 'Maine', 'D1-FCS', 'CAA'),
('Marist', 'New York', 'D1-FCS', 'Pioneer League'),
('McNeese State', 'Louisiana', 'D1-FCS', 'Southland'),
('Mercer', 'Georgia', 'D1-FCS', 'SOCON'),
('Merrimack College', 'Massachusetts', 'D1-FCS', 'NEC'),
('Mississippi Valley State', 'Mississippi', 'D1-FCS', 'SWAC'),
('Missouri State', 'Missouri', 'D1-FCS', 'Missouri Valley'),
('New Hampshire', 'New Hampshire', 'D1-FCS', 'CAA'),
('Norfolk State', 'Virginia', 'D1-FCS', 'MEAC'),
('North Carolina A&T', 'North Carolina', 'D1-FCS', 'MEAC'),
('North Carolina Central', 'North Carolina', 'D1-FCS', 'MEAC'),
('North Dakota State', 'North Dakota', 'D1-FCS', 'Missouri Valley'),
('Penn', 'Pennsylvania', 'D1-FCS', 'Ivy League'),
('Prairie View A&M', 'Texas', 'D1-FCS', 'SWAC'),
('Presbyterian College', 'South Carolina', 'D1-FCS', 'Pioneer League'),
('Princeton', 'New Jersey', 'D1-FCS', 'Ivy League'),
('Richmond', 'Virginia', 'D1-FCS', 'CAA'),
('Sacred Heart', 'Connecticut', 'D1-FCS', 'NEC'),
('Sam Houston State', 'Texas', 'D1-FCS', 'WAC'),
('Samford', 'Alabama', 'D1-FCS', 'SOCON'),
('South Dakota', 'South Dakota', 'D1-FCS', 'Missouri Valley'),
('Southern Illinois', 'Illinois', 'D1-FCS', 'Missouri Valley'),
('Stetson', 'Florida', 'D1-FCS', 'Pioneer League'),
('Stony Brook', 'New York', 'D1-FCS', 'CAA'),
('Tennessee State', 'Tennessee', 'D1-FCS', 'OVC'),
('Texas A&M-Commerce', 'Texas', 'D1-FCS', 'Southland'),
('Towson', 'Maryland', 'D1-FCS', 'CAA'),
('UT Martin', 'Tennessee', 'D1-FCS', 'OVC'),
('Valparaiso University', 'Indiana', 'D1-FCS', 'Pioneer League'),
('VMI', 'Virginia', 'D1-FCS', 'SOCON'),
('Western Carolina', 'North Carolina', 'D1-FCS', 'SOCON'),
('William & Mary', 'Virginia', 'D1-FCS', 'CAA'),
('Yale', 'Connecticut', 'D1-FCS', 'Ivy League')
ON CONFLICT (name) DO NOTHING;